"""Code generation service — DEVPIPE-03.

Builds a structured prompt from the Jira issue, Confluence architecture page,
and codebase context, then calls freellmapi via route_request('codegen', ...)
to generate file-level code changes.

The LLM is prompted to respond with structured sections using the convention:
  ### FILE: path/to/file.py
  ```python
  <full file content>
  ```

This module parses those sections into FileChange dataclass instances that the
pr_creator can apply to the cloned workspace.

Threat mitigations:
  T-06-01: Prompt contains only issue_key/summary/description/architecture/
            codebase_context — no token or credential values interpolated.
  T-06-02: Graceful fallback on empty/stub LLM output — returns [] rather
            than raising, so callers can post a "no changes generated" comment.
"""

import logging
import re
from dataclasses import dataclass, field

from services.llm_router import route_request

logger = logging.getLogger(__name__)


@dataclass
class FileChange:
    """A single file-level code change generated by the LLM.

    Fields:
        path:    Relative file path within the repository (e.g. "backend/main.py").
        content: Full file content to write (new or replacement content).
    """

    path: str
    content: str


def _parse_file_changes(llm_output: str) -> list[FileChange]:
    """Parse structured LLM output into FileChange instances.

    Expected LLM output format (one or more blocks):
      ### FILE: path/to/file.py
      ```python
      <file content>
      ```

    Also handles:
      ### FILE: path/to/file.js
      ```javascript
      <file content>
      ```

    Or plain code blocks without language specifiers:
      ### FILE: path/to/file.py
      ```
      <file content>
      ```

    Non-conforming output (no FILE sections) returns an empty list — callers
    should treat this as "no changes generated" (T-06-02 graceful degradation).

    Args:
        llm_output: Raw LLM response text.

    Returns:
        List of FileChange instances (may be empty if output is malformed/stub).
    """
    changes: list[FileChange] = []

    if not llm_output or llm_output.strip() in ("[stub]", ""):
        logger.warning("LLM returned empty or stub output — no file changes generated")
        return changes

    # Match ### FILE: <path> blocks followed by a code fence
    # Pattern: ### FILE: <path>\n```[optional-lang]\n<content>\n```
    pattern = re.compile(
        r"###\s*FILE:\s*([^\n]+)\n```[^\n]*\n(.*?)```",
        re.DOTALL,
    )

    for match in pattern.finditer(llm_output):
        file_path = match.group(1).strip()
        content = match.group(2)

        # Normalise the path: strip leading slashes or ./ prefix
        file_path = file_path.lstrip("/").lstrip("./")

        if not file_path:
            logger.warning("Skipping FILE block with empty path")
            continue

        changes.append(FileChange(path=file_path, content=content))
        logger.info("Parsed file change for: %s", file_path)

    if not changes:
        logger.warning(
            "LLM output did not contain any ### FILE: blocks — no file changes generated"
        )

    return changes


def generate_code_changes(
    issue_key: str,
    issue_summary: str,
    issue_description: str,
    architecture_content: str,
    codebase_context: str,
) -> list[FileChange]:
    """Generate file-level code changes for a Jira issue via freellmapi.

    DEVPIPE-03: Given Jira description, Confluence architecture content, and
    codebase context, the agent calls freellmapi (codegen stage) and receives
    parsed file-level code changes.

    T-06-01: Only issue_key/summary/description/architecture/codebase context
    are interpolated into the prompt — no token or credential values included.

    Args:
        issue_key:            Jira issue key (e.g. "PROJ-42").
        issue_summary:        Issue summary field.
        issue_description:    Issue description (plain text).
        architecture_content: Architecture page content fetched from Confluence
                              (plain text or markdown).
        codebase_context:     Codebase directory tree and key module docstrings
                              (plain text summary from graphify_service).

    Returns:
        List of FileChange instances. Empty list if LLM returns no parseable
        changes (e.g. stub response on freellmapi failure) — callers should
        handle this gracefully.
    """
    logger.info("Generating code changes for ticket %s", issue_key)

    # T-06-01: prompt contains only issue data + architecture + codebase context
    prompt = (
        "You are a senior software engineer implementing a Jira story. "
        "Generate the exact file changes needed to implement the following story.\n\n"
        f"Jira Ticket: {issue_key}\n"
        f"Summary: {issue_summary}\n"
        f"Description:\n{issue_description}\n\n"
        "Architecture Design:\n"
        f"{architecture_content}\n\n"
        "Existing Codebase Structure:\n"
        f"{codebase_context}\n\n"
        "IMPORTANT: Respond with ONLY the file changes needed. "
        "For each file to create or modify, use EXACTLY this format:\n\n"
        "### FILE: path/to/file.py\n"
        "```python\n"
        "<complete file content here>\n"
        "```\n\n"
        "Rules:\n"
        "- Include complete file content (not diffs or partial snippets)\n"
        "- Use the exact ### FILE: format for each file\n"
        "- Only include files that need to be created or modified\n"
        "- File paths should be relative to the repository root\n"
        "- Do not include explanations outside of the file blocks"
    )

    route_result = route_request("codegen", prompt)
    return _parse_file_changes(route_result.content)
